services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - PORT=4000
    depends_on:
      - postgres
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 10s
      retries: 10

  frontend:
    image: node:lts
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 3001:5173
    environment:
      - VITE_API_URL=http://localhost:4000
    command: sh -c "npm install && npm run dev"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres-data:
  backend-node-modules:
